#!/usr/bin/env python3
"""
TEST DOUBLE - this is NOT a language model and NOT Ollama.

A tiny stdlib HTTP server that speaks the subset of the Ollama wire protocol
the Moltress agent layer uses (GET /api/tags, POST /api/chat with
stream=false and optional format=json). It lets the whole chain
(UI -> backend -> agents -> *real* OllamaClient over real HTTP) be exercised on
machines that cannot run a 7B model, e.g. CI or a sandbox.

What it validates (like real Ollama would):
  * the request is JSON with `model` and `messages`
  * the requested model matches --model, else HTTP 404 {"error": "model ... not found"}

What it does NOT do: reason. Its replies are scripted from the *real* tool
results it is shown (e.g. the actual file count the agent's inspect_project
tool returned), so tests can prove real tool output flowed through the loop.

Modes (switch at runtime with POST /__control {"mode": "..."}):
  ok          route -> tool call (inspect_project) -> final JSON answer
  malformed   final answer violates the agent's schema      (-> MalformedOutput)
  http500     /api/chat returns HTTP 500                    (-> LLMUnavailable)
  hang        /api/chat never answers                       (-> timeout)

Usage:  python scripts/e2e/ollama_protocol_server.py --port 11435 --model qwen2.5-coder:7b
Every chat request is appended to --log (JSON lines) for assertions.
"""

from __future__ import annotations

import argparse
import json
import re
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

STATE = {"mode": "ok"}


def _last_tool_result(messages):
    for m in reversed(messages):
        if m.get("role") == "user" and str(m.get("content", "")).startswith("## Tool Result:"):
            return str(m["content"])
    return None


def _scripted_reply(payload: dict) -> str:
    messages = payload.get("messages", [])
    system = (messages[0].get("content", "") if messages else "")

    # 1. Router LLM-fallback classification (plain text label).
    if system.lstrip().startswith("You are a routing classifier"):
        return "developer_agent"

    # 2. Agent turn. After a tool result -> final answer; otherwise ask for a tool.
    tool_result = _last_tool_result(messages)
    if tool_result is None:
        return json.dumps({
            "action": "use_tool",
            "tool_name": "inspect_project",
            "tool_arguments": {"directory": "."},
            "reasoning": "Inspect the project structure to explain its purpose.",
        })

    if STATE["mode"] == "malformed":
        return json.dumps({"status": "success", "result": "x", "findings": "not-a-list", "assumptions": 5})

    m = re.search(r"total_files\W+(\d+)", tool_result)
    files = m.group(1) if m else "an unknown number of"
    first_user = next((x["content"] for x in messages if x.get("role") == "user"), "")
    q = re.search(r"## User Query\n(.*?)\n\n", first_user, re.S)
    return json.dumps({
        "status": "success",
        "result": (
            f"[protocol-test-double] Answering: {q.group(1).strip() if q else '?'}\n\n"
            f"I inspected the project with the inspect_project tool: it contains {files} files. "
            "This reply is scripted by the Ollama protocol test double, not generated by a model."
        ),
        "explanation": "Based on the real output of the inspect_project tool.",
        "confidence": "medium",
        "confidence_score": 0.5,
        "evidence": [{"source": "inspect_project", "excerpt": f"total_files={files}"}],
    })


def make_handler(model: str, log_path: str | None):
    class Handler(BaseHTTPRequestHandler):
        protocol_version = "HTTP/1.1"

        def log_message(self, *a):  # quiet
            pass

        def _send(self, code: int, body: dict):
            data = json.dumps(body).encode()
            self.send_response(code)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)

        def do_GET(self):
            if self.path == "/api/tags":
                self._send(200, {"models": [{"name": model, "model": model}]})
            elif self.path == "/__state":
                self._send(200, STATE)
            else:
                self._send(404, {"error": "not found"})

        def do_POST(self):
            n = int(self.headers.get("Content-Length", 0))
            raw = self.rfile.read(n) if n else b""
            try:
                payload = json.loads(raw or b"{}")
            except json.JSONDecodeError:
                return self._send(400, {"error": "invalid JSON"})

            if self.path == "/__control":
                STATE["mode"] = payload.get("mode", "ok")
                return self._send(200, STATE)

            if self.path != "/api/chat":
                return self._send(404, {"error": "not found"})
            if "model" not in payload or "messages" not in payload:
                return self._send(400, {"error": "model and messages are required"})
            if payload["model"] != model:
                return self._send(404, {"error": f"model '{payload['model']}' not found, try pulling it first"})

            if log_path:
                with open(log_path, "a", encoding="utf-8") as fh:
                    fh.write(json.dumps({
                        "t": time.time(), "model": payload["model"], "format": payload.get("format"),
                        "stream": payload.get("stream"), "n_messages": len(payload["messages"]),
                        "options": payload.get("options"),
                        "last_user": next((m["content"][:200] for m in reversed(payload["messages"]) if m["role"] == "user"), ""),
                    }) + "\n")

            if STATE["mode"] == "http500":
                return self._send(500, {"error": "simulated server failure"})
            if STATE["mode"] == "hang":
                time.sleep(3600)
            content = _scripted_reply(payload)
            self._send(200, {
                "model": payload["model"], "created_at": "2026-01-01T00:00:00Z",
                "message": {"role": "assistant", "content": content}, "done": True,
            })

    return Handler


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=11435)
    ap.add_argument("--model", default="qwen2.5-coder:7b")
    ap.add_argument("--log", default=None, help="append each chat request as a JSON line")
    a = ap.parse_args()
    srv = ThreadingHTTPServer((a.host, a.port), make_handler(a.model, a.log))
    srv.daemon_threads = True
    print(f"[TEST DOUBLE - not a model] Ollama protocol server on http://{a.host}:{a.port} (model={a.model})", flush=True)
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
